context:
  version: 1.4.5

package:
  name: grex
  version: ${{ version }}

source:
  url: https://github.com/pemistahl/grex/archive/v${{ version }}.tar.gz
  sha256: 4e849b29b387afc583856f24923b76052ad90e320c2caacfc6452e6d9deb6b14

build:
  number: 0

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - cargo-bundle-licenses

tests:
  - script:
      - grex --help

about:
  license: Apache-2.0
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: Command-line tool for generating regular expressions
  homepage: https://github.com/pemistahl/grex
  repository: https://github.com/pemistahl/grex

extra:
  recipe-maintainers:
    - danielnachun
